//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VisualText.rc
//
#define IDS_ABOUTBOX                    101
#define IDR_POPUP                       102
#define IDR_MAINFRAME                   128
#define IDR_GUI_VITYPE                  129
#define IDS_FIND                        129
#define IDB_IMGLIST_TAB                 130
#define ID_HELP_TIPOFTHEDAY             130
#define IDB_IMGLIST_VIEW                131
#define IDR_POPUP_WORKSPACE             133
#define IDR_POPUP_STANDARD              134
#define IDR_POPUP_WIZARD                143
#define IDR_DEBUG                       154
#define IDB_WORKSPACE                   163
#define IDB_IL_TAB                      167
#define IDB_IL_FILE                     168
#define IDR_KNOWLEDGE                   170
#define IDB_TEXT                        171
#define IDI_ICON1                       173
#define IDR_BROWSER_MENU                174
#define IDR_KNOWLEDGE_MENU              175
#define IDR_PARSETREE                   176
#define IDR_TEXT_EDITOR                 177
#define IDR_ANALYZER                    178
#define IDR_TAB                         290
#define IDC_TXT_URL                     1000
#define IDC_FLATTABCTRL                 1001
#define IDC_TXT_EMAIL                   1001
#define IDC_CHK_ADDRESS                 1001
#define IDC_SHEET1                      1002
#define IDC_TXT_COPYRIGHT               1002
#define IDC_CHK_HEXCODE                 1002
#define IDC_SHEET2                      1003
#define IDC_TXT_TITLE                   1003
#define IDC_CHK_ASCII                   1003
#define IDC_SHEET3                      1004
#define IDC_TXT_APPNAME                 1004
#define IDC_CHK_WIDE_ADDRESS            1004
#define IDC_FIND2                       1004
#define IDC_SHEET4                      1005
#define IDC_CHECK_48                    1005
#define IDC_SLIDER                      1005
#define IDC_KB_FILES                    1005
#define IDC_SHEET5                      1006
#define IDC_SLIDER1                     1006
#define IDC_HEXEDIT                     1006
#define IDC_TIP_OF_DAY                  1006
#define IDC_SHEET6                      1007
#define IDC_HEXEDIT1                    1007
#define IDC_EDIT_BASEADDR               1007
#define IDC_INPUT_FILES                 1007
#define IDC_TXT_BASEADDR                1008
#define IDC_QUICK_EDIT_BOX              1008
#define IDC_TXT_BYTE                    1009
#define IDC_STATIC_ATTRIBUTE            1009
#define IDC_CHK_ENABLE                  1010
#define IDC_STATIC_VALUE                1010
#define IDC_CLR_BACK_ENABLED            1011
#define IDC_STATIC_TABLE                1011
#define IDC_CLR_TEXT_ENABLED            1012
#define IDC_                            1012
#define IDC_ATTRIBUTE_BOX               1012
#define IDC_CLR_BACK_DISABLED           1013
#define IDC_DICTIONARY_TOOLS_BOX        1013
#define IDC_CLR_TEXT_DISABLED           1014
#define IDC_TABBED_WINDOWS              1014
#define IDC_CLR_BACK_HILITE_ENABLED     1015
#define IDC_TOOLBAR_LABELS              1015
#define IDC_CLR_TEXT_HILITE_ENABLED     1016
#define IDC_ACSII_DISPLAY               1016
#define IDC_CLR_BACK_HILITE_DISABLED    1017
#define IDC_CLR_TEXT_HILITE_DISABLED    1018
#define IDC_GBOX_ENABLED                1019
#define IDC_GBOX_DISABLED               1020
#define IDC_CHK_CARET                   1021
#define IDC_TXT_ENABLED                 1022
#define IDC_TXT_DISABLED                1023
#define IDC_TXT_BACK_ENABLED            1024
#define IDC_TXT_TEXT_ENABLED            1025
#define IDC_TXT_BACK_HILITE_ENABLED     1026
#define IDC_TXT_TEXT_HILITE_ENABLED     1027
#define IDC_TXT_BACK_DISABLED           1028
#define IDC_TXT_TEXT_DISABLED           1029
#define IDC_TXT_BACK_HILITE_DISABLED    1030
#define IDC_TXT_TEXT_HILITE_DISABLED    1031
#define IDC_CHK_ALLOWDEL                1032
#define IDC_CHK_READONLY                1033
#define IDC_STATIC_1                    1153
#define IDC_EDIT1                       1154
#define IDC_STATIC_2                    1156
#define IDC_EDIT2                       1157
#define IDC_STATIC_3                    1160
#define IDC_EDIT3                       1161
#define IDC_STATIC_4                    1164
#define IDC_EDIT4                       1165
#define IDC_STATIC_5                    1168
#define IDC_EDIT5                       1169
#define IDC_CHECK1                      1172
#define IDC_STATIC_6                    1176
#define IDC_EDIT6                       1177
#define IDC_STATIC_7                    1180
#define IDC_EDIT7                       1181
#define IDC_STATIC_8                    1182
#define IDC_CHECK2                      1186
#define IDC_CHECK3                      1187
#define IDC_CHECK4                      1188
#define IDC_CHECK5                      1189
#define IDC_CHECK6                      1190
#define IDC_CHECK7                      1191
#define IDC_EDIT8                       1192
#define IDC_CHECK8                      1195
#define IDC_STATIC_9                    1196
#define IDC_EDIT9                       1197
#define IDC_CHECK9                      1200
#define IDC_TAB1                        1264
#define IDR_RICHYTYPE_CNTR_IP           2000
#define IDP_OLE_INIT_FAILED             2001
#define IDD_HEXEDIT_DIALOG              2004
#define IDR_ANALYZERSEQVIEW_TMPL        2005
#define IDR_ANALYZERSEQ                 2006
#define IDD_ANALYZERVIEW_FORM           2007
#define IDR_ANALYZERVIEW_TMPL           2008
#define IDD_TESTDIALOG_DIALOG           2009
#define IDS_COL_1                       2010
#define IDS_COL_2                       2011
#define IDC_LIST_CTRL_1                 2012
#define IDC_LIST_CTRL_2                 2013
#define IDB_ATTR_EDITOR_VALUE_ICONS     2014
#define IDR_MAINFRAME_TOOLBAR           2016
#define IDR_VISUALTYPE                  2017
#define IDD_SETTINGS_DLG                2018
#define IDD_ANALYZER_SETTINGS_DLG       2019
#define IDB_FIRST_TREE_ICON             2020
#define IDD_RULE_LIST_DIALOG            2021
#define IDD_ARCHIVE_LIST_DIALOG         2022
#define IDD_ANALYZER_SEQ_DLG            2023
#define IDB_LAST_TREE_ICON              2024
#define IDB_UP                          2025
#define IDB_DOWN                        2026
#define IDI_TEXT                        2027
#define IDI_FOLDER_CLOSED               2028
#define IDI_FOLDER_OPEN                 2029
#define IDI_URL                         2030
#define IDR_TREEVIEWTEXT                2031
#define IDD_LOAD_ANALYZER               2033
#define IDD_ARCHIVE_PROGRESS            2034
#define IDD_ASK_TEXT_DIALOG             2035
#define IDD_NLP_PREFERENCES             2036
#define IDD_VISUALTEXT_PREFERENCES      2037
#define IDB_BIG_LOGO                    2038
#define IDD_INIT_NLPLITE                2039
#define IDI_LOG                         2040
#define IDI_LOG_FOLDER                  2041
#define IDI_TEXT_ANALYZED               2042
#define IDI_URL_ANALYZED                2043
#define IDR_HELP                        2044
#define IDR_DEBUG_TOOLBAR               2045
#define IDR_SEQUENCE_CONTEXT            2046
#define IDR_RULEFILE                    2048
#define IDR_LOGGING                     2049
#define IDD_PARSETREE                   2051
#define IDD_DIALOG1                     2053
#define IDS_FTPMSG2                     2054
#define IDS_FTPMSG3                     2055
#define IDS_FTPMSG4                     2056
#define IDI_NODE                        2057
#define IDS_FTPMSG5                     2058
#define IDI_LEAF                        2059
#define IDS_FTPMSG6                     2060
#define IDI_RULE                        2061
#define IDS_SOCKETS_INIT_FAILED         2062
#define IDS_FTPMSG1                     2063
#define IDB_IL_CLASS                    2064
#define IDS_STRING2064                  2064
#define IDS_ABOUT                       2064
#define IDB_IL_RSRC                     2065
#define IDB_ANALYZER                    2066
#define IDR_GRAMMAR                     2069
#define IDR_BROWSER_TOOLBAR             2070
#define IDB_GRAMMAR                     2071
#define IDI_TEXT_SELECTED               2072
#define IDI_TEXT_ANALYZED_SELECTED      2073
#define IDR_LOGFILE                     2074
#define IDR_TEXTVIEW                    2075
#define IDR_BROWSER                     2076
#define IDR_TEXT                        2077
#define IDR_RULE                        2078
#define IDR_LOG                         2079
#define IDR_FIND                        2080
#define IDD_ATTRIBUTE_EDITOR            2081
#define IDB_ATTRIBUTES                  2082
#define IDD_NEW_ANALYZER                2083
#define IDR_OUTPUT                      2084
#define IDB_OUTPUT                      2085
#define IDD_RECORD_PROPERTIES           2086
#define IDD_TREE_CHOOSE                 2087
#define IDD_GRAM_CONCEPT                2088
#define IDD_OUTPUT_ITEM_DLG             2089
#define IDD_CHOOSE_SAMPLE               2090
#define IDR_SAMPLE                      2091
#define IDB_GATHER_UP                   2092
#define IDB_GATHER_DOWN                 2093
#define IDB_DRAG_UP                     2094
#define IDB_DRAG_DOWN                   2095
#define IDB_TEAR_DOWN                   2096
#define IDB_TEAR_UP                     2097
#define IDB_TEAR_DOWN_GRAY              2098
#define IDD_SPLASH_DLG                  2099
#define IDR_TREE                        2100
#define IDD_FIND_DLG                    2101
#define IDD_PASS_PROPERTIES_DLG         2102
#define IDR_PARSETREE_POPUP             2103
#define IDR_KNOWLEDGE_TOOLBAR           2104
#define IDR_TAB_TOOLBAR                 2105
#define IDI_URL_SELECTED                2106
#define IDI_URL_ANALYZED_SELECTED       2107
#define IDB_KNOWLEDGE                   2108
#define IDI_KNOWLEDGE                   2111
#define IDD_PHRASES_DLG                 2112
#define IDD_SLOT_DLG                    2113
#define IDD_ARCHIVE_NAME_DLG            2114
#define IDB_BROWSER                     2115
#define IDB_URL                         2116
#define IDD_TEXT_INFO                   2118
#define IDB_PARSE_TREE                  2119
#define IDD_DICTIONARY_DLG              2120
#define IDB_NO_ATTRS                    2121
#define IDR_DICTIONARY_WORDS            2122
#define IDD_ASCII_DLG                   2123
#define IDD_CHAR_VIEWER                 2124
#define IDD_EMAIL_DLG                   2125
#define IDD_PREF_DISPLAY_PAGE           2126
#define IDD_PREF_EMAIL_PAGE             2127
#define IDD_PREF_GENERAL_PAGE           2128
#define IDD_PREF_ARCHIVE                2129
#define IDD_CUSTOM_MSG_DLG              2130
#define IDB_YIELD                       2131
#define IDR_WAVE_STUPID                 2132
#define IDR_WAVE_LOSTBOY                2133
#define IDR_WAVE_RULEJOCKEY             2134
#define IDR_WAVE_WHOOPS                 2135
#define IDD_REGISTRATION_DLG            2136
#define IDD_CHOOSE_DIR_DLG              2137
#define IDB_VT_LOGO                     2138
#define IDD_SEMPOPUP                    2139
#define IDD_PREF_LOOKUP                 2140
#define IDB_BITMAP1                     2141
#define IDC_STATIC_ANALZYER             2142
#define IDC_DIRECTORY_NAME              2143
#define IDC_ANALYZER_NAME               2144
#define IDC_DIRECTORY_TREE              2145
#define IDC_STATIC_LOCATION             2146
#define IDC_CHECK_ADDRESS               2147
#define IDC_DRIVE_COMBO                 2148
#define IDC_ANALYZER_LOCATION           2149
#define IDC_CHECK_HEXCODE               2150
#define IDC_RULE_LIST                   2151
#define IDC_ARCHIVE_LIST                2152
#define IDC_CHECK_ASCII                 2153
#define IDC_NEW                         2154
#define IDC_ANALYZER_LIST               2156
#define IDC_COMMENTS                    2159
#define IDC_FILE                        2160
#define IDC_DATA                        2161
#define IDC_ACTIVE                      2162
#define IDC_TYPE                        2163
#define IDC_ALGO                        2164
#define IDC_DELETE                      2165
#define IDC_UPDATE                      2166
#define IDC_STATUS                      2167
#define IDC_SAVE                        2168
#define IDC_RUN                         2169
#define IDC_UP                          2170
#define IDC_DOWN                        2171
#define IDC_MATCH_WHOLE_WORD            2172
#define IDC_DEBUG                       2173
#define IDC_DIRTREE                     2174
#define IDC_ADD_URL                     2175
#define IDC_GO_URL                      2176
#define IDC_URL_PATH_EX                 2177
#define IDC_PROGRESS1                   2178
#define IDC_PROGRESS                    2179
#define IDC_MSG                         2180
#define IDC_USER_TEXT                   2181
#define IDC_RELOAD                      2182
#define IDC_COMMENT_STATIC              2183
#define IDC_ANALYZER_COMMENTS           2184
#define IDC_AUTOLOAD                    2185
#define IDC_LAST_ANALYZER_TEXT          2186
#define IDC_LOADING_MESSAGE             2187
#define IDC_PROCESS_FILE                2188
#define IDC_PARSETREE                   2189
#define IDC_FULL_SCREEN                 2190
#define IDC_USER_LOGFILE                2191
#define IDC_ARCHIVE_NAME                2192
#define IDC_DOWNLOAD                    2193
#define IDC_RENAME                      2194
#define IDC_ARCHIVE_MESSAGE             2195
#define IDC_ARCHIVE_PROGRESS_MESSAGE    2196
#define IDC_LOAD                        2197
#define IDC_LOCATION                    2198
#define IDC_TEMPLATE_LIST               2199
#define IDC_ADD                         2200
#define IDC_ADDVALUE                    2201
#define IDC_ATTRIBUTE_LIST              2202
#define IDC_ORDER_BY                    2203
#define IDC_PREV                        2204
#define IDC_FIRST                       2205
#define IDC_NEXT                        2206
#define IDC_INCLUDE_LAST                2207
#define IDC_SEARCH                      2208
#define IDC_RECORD_NAME                 2209
#define IDC_ZONE_BUTTON                 2210
#define IDC_ZONE                        2211
#define IDC_LABEL                       2212
#define IDC_TREE_CHOICES                2213
#define IDC_CHILDREN                    2214
#define IDC_UNCHECK                     2215
#define IDC_NAME                        2216
#define IDC_CLOSED                      2217
#define IDC_LITERAL                     2218
#define IDC_CONSTRAINED                 2219
#define IDC_SPLIT                       2220
#define IDC_GENERALIZED                 2221
#define IDC_FOLDER_LOG                  2222
#define IDC_QUICKSEM                    2223
#define IDC_REQUIRED                    2224
#define IDC_RAW                         2225
#define IDC_NORMAL_FORM                 2226
#define IDC_CLOSED_INHERITED            2227
#define IDB_ADD                         2228
#define IDC_CONSTRAINED_INHERITED       2229
#define IDB_REMOVE                      2230
#define IDC_GENERALIZED_INHERITED       2231
#define IDB_UPDATE                      2232
#define IDB_KB_EDIT                     2233
#define IDC_SPLIT_INHERITED             2234
#define IDC_RAW_INHERITED               2235
#define IDC_LITERAL_INHERITED           2236
#define IDC_QUICKSEM_INHERITED          2237
#define IDC_WHITESPACE_INHERITED        2238
#define IDC_WHITESPACE                  2239
#define IDC_SLOG_WINDOW                 2240
#define IDC_HELP_RULE_GENERATION        2241
#define IDC_CANCEL                      2242
#define IDE_FIND                        2243
#define IDE_REPLACE                     2245
#define IDC_DOWN1                       2247
#define IDC_DOWN2                       2250
#define IDC_UP2                         2251
#define IDC_DOWN3                       2254
#define IDC_UP3                         2255
#define IDC_DOWN4                       2258
#define IDC_UP4                         2259
#define IDC_DOWN5                       2262
#define IDC_UP5                         2263
#define IDC_LOCKED                      2265
#define IDC_LOCKED_INHERITED            2266
#define IDC_SAMPLE                      2267
#define IDC_BROWSE                      2269
#define IDC_SAMPLE_FILE                 2271
#define IDC_DOWN6                       2272
#define IDC_UP6                         2273
#define IDC_UP7                         2277
#define IDC_DOWN7                       2278
#define IDC_SPECIAL                     2279
#define IDC_UP1                         2280
#define ID_FILE_FIND                    2285
#define IDC_UP8                         2289
#define IDC_DOWN8                       2290
#define IDC_UP9                         2294
#define IDC_DOWN9                       2295
#define IDC_DRAG_UP                     2297
#define IDC_DRAG_DOWN                   2298
#define IDC_TEAR_UP                     2299
#define IDC_TEAR_DOWN                   2300
#define IDC_GATHER_UP                   2301
#define IDC_GATHER_DOWN                 2302
#define IDC_REVERT                      2303
#define IDC_MOVE_ALL                    2304
#define IDC_MOVE_ONE                    2305
#define IDC_TEAR                        2306
#define IDC_JOIN                        2307
#define IDC_MESSAGE                     2308
#define IDC_DRAG                        2309
#define IDC_AUTHOR_NAME                 2310
#define IDC_MATCH_CASE                  2311
#define IDC_FIND_STR                    2312
#define IDC_LOG_FILES                   2313
#define IDC_CONCEPTS                    2314
#define IDC_RULE_FILES                  2315
#define IDC_OTHER_RULE_FILES            2316
#define IDC_TEXT_FILES                  2317
#define IDC_APPEND                      2318
#define IDC_OUTPUT_FILES                2319
#define IDC_LAYER_STRING                2320
#define IDC_ATTRIBUTES                  2321
#define IDC_LIST                        2322
#define IDC_OUTPUT_LIST                 2323
#define IDC_PRINT_NAME                  2324
#define IDC_FIELD_NAME                  2325
#define IDC_SAVE_LOG_FILES              2326
#define IDC_LINE_COUNT                  2327
#define IDC_CHARACTER_COUNT             2328
#define IDC_WORD_COUNT                  2329
#define IDC_FILE_SIZE                   2330
#define IDC_CREATED                     2331
#define IDC_FILE_PATH                   2332
#define IDC_LAST_MODIFIED               2333
#define IDC_DICTIONARY_LIST             2334
#define IDC_BACK                        2335
#define IDC_FORWARD                     2336
#define IDC_BACK_LETTER                 2337
#define IDC_FORWARD_LETTER              2338
#define IDC_WORD                        2339
#define IDC_COUNT                       2341
#define IDC_ATTRS_DISPLAY               2342
#define IDC_ADD_LIST                    2343
#define IDC_MOVE_TO_LIST                2344
#define IDC_CLEAR_LIST                  2345
#define IDC_DELETE_ALL                  2346
#define IDC_ATTRIBUTE_TOGGLE            2347
#define IDC_CLEAR_ALL                   2348
#define IDC_FIND_TYPE                   2349
#define IDC_ADD_ALL                     2350
#define IDC_TO_DICT                     2351
#define IDC_BUTTON_ASCII                2352
#define IDC_DELETE_WORD                 2353
#define IDC_CHAR_DISPLAY                2354
#define IDC_AUTOSIZE_WINDOWS            2355
#define IDC_MAX_WINDOW_WIDTH            2356
#define IDC_MAX_WINDOW_HEIGHT           2357
#define IDC_SMTP_SERVER                 2358
#define IDC_FROM_EMAIL                  2359
#define IDC_BODY                        2360
#define IDC_TO                          2361
#define IDC_SUBJECT                     2362
#define IDC_PREF_PROP_SHEET             2363
#define IDC_PASSWORD                    2364
#define IDC_USERNAME                    2365
#define IDC_ARCHIVE_FTP                 2366
#define IDC_DIRECTORY_PATH              2367
#define IDC_RULE_TAB_SIZE               2368
#define IDC_VERSION                     2369
#define IDC_FONT_SIZE                   2370
#define IDC_DYNAMIC_SIZE                2371
#define IDC_EMAIL_LIST_CHOOSE           2372
#define IDC_EMAIL_LIST                  2373
#define IDC_PREVIOUS_EMAIL              2374
#define IDC_NEXT_EMAIL                  2375
#define IDC_SEND_CURRENT                2376
#define IDC_LOAD_COMPILED_KB            2377
#define IDC_AUTOSAVE_KB                 2378
#define IDC_COPYRIGHT                   2379
#define IDC_KB_SAFE_EDIT_MODE           2380
#define IDC_REGISTRATION_NUMBER         2381
#define IDC_APPS_DIRECTORY              2382
#define IDC_SAVE_C_FILES                2383
#define IDC_ARCHIVE_PATH                2384
#define IDC_PATH                        2385
#define IDC_TO_END                      2386
#define IDC_FROM                        2387
#define IDC_ALL                         2388
#define IDE_DIRECTORY                   2389
#define IDC_RULES_RECURSIVE             2390
#define IDC_TEXT_RECURSIVE              2391
#define IDC_DIRECTORY_RECURSIVE         2392
#define IDC_FILESPEC                    2393
#define IDE_SEARCH                      2394
#define IDC_ADD_NOUN                    2395
#define IDC_ADD_VERB                    2396
#define IDC_ADD_ADJ                     2397
#define IDC_ADD_ADVERB                  2398
#define IDC_NO_ATTRS                    2399
#define IDC_OPEN_KB                     2400
#define IDC_QUICKEDIT                   2401
#define IDC_LISTQUICKEDIT               2402
#define IDE_ATTRIBUTE                   2403
#define IDE_VALUE                       2404
#define IDB_QUICKEDITHELP               2405
#define IDC_BUTTON1                     2406
#define IDC_ADD_WORD                    2407
#define IDE_TEXT                        2408
#define IDC_LOOKUP                      2409
#define IDC_LOOKUP_LIST                 2410
#define IDE_NAME                        2411
#define IDE_URL                         2412
#define IDC_COMBO_LOOKUP                2413
#define IDC_ANALYZER                    2414
#define IDC_BROWSE_CONCEPT              2415
#define IDC_VALUE_TYPE                  2416
#define IDD_REPLACE_IN_FILES            2417
#define IDD_PREF_ANALYZER_DEPENDENT_PAGE 2418
#define IDC_ANALYZER_TREE_SELECT        2419
#define ID_CANCEL_EDIT_CNTR             2423
#define ID_PAGE_SETUP                   2424
#define ID_ANALYZER_SETTINGS            2425
#define ID_ANALYZER_SEQUENCE            2426
#define ID_BUILD_BUILDANALYZER          2427
#define ID_BUILD_RUNANALYZER            2428
#define ID_ANALYZER_RULES               2429
#define ID_ANALYZER_DICITIONARY         2430
#define ID_BUILD_URL                    2431
#define ID_DIRTREEMENU_VIEWASWEBPAGE    2432
#define ID_OPTIONS_STOP                 2433
#define ID_OPTIONS_BACK                 2434
#define ID_DIRTREEMENU_DELETE           2435
#define ID_DIRTREEMENU_ADDFOLDER        2436
#define ID_DIRTREEMENU_ADDTOPLEVELFOLDER 2437
#define ID_BACK_URL                     2438
#define ID_FORWARD_URL                  2439
#define ID_FILE_PREFERENCES             2440
#define ID_DIRTREEMENU_RENAME           2441
#define ID_DIRTREEMENU_VIEWOUTPUTFILE   2442
#define ID_HELP_VISUALTEXTHELP          2443
#define ID_OPTIONS_FORWARD              2444
#define ID_DIRTREEMENU_HELP             2445
#define ID_HELP_HELP                    2446
#define ID_LOGGING_CLEARLOG             2447
#define ID_LOGGING_HELP                 2448
#define ID_DIRTREEMENU_RUNANALYZER      2449
#define ID_SEQUENCEMENU_NEW             2450
#define ID_SEQUENCEMENU_DELETE          2451
#define ID_SEQUENCEMENU_HELP            2452
#define ID_SEQUENCEMENU_EDITVIEW        2453
#define ID_DIRTREEMENU_EDITVIEW         2454
#define ID_URL_STOP                     2455
#define ID_SEQUENCEMENU_VIEWOUTPUT      2456
#define ID_SEQUENCEMENU_EDITRULES       2457
#define ID_DIRTREEMENU_NEWTEXT          2458
#define ID_DIRTREEMENU_ADDEXISTINGTEXT  2459
#define ID_RULEFILE_RULEHELP            2460
#define ID_RULEFILE_FIND                2461
#define ID_RULEFILE_FINDWORD            2462
#define ID_EDIT_FILE                    2462
#define ID_PARSETREE_HELP               2463
#define ID_SEQUENCEMENU_VIEWCONCEPTTREE 2464
#define ID_DIRTREEMENU_DELETECHILDREN   2465
#define ID_RULEFILE_CLOSEALL            2466
#define ID_DIRTREEMENU_MOVETOTOPLEVEL   2467
#define ID_SEQUENCEMENU_ADDEXISTINGRULES 2468
#define ID_DIRTREEMENU_UPDATEWEBPAGE    2469
#define ID_RULEFILE_FINDAGAIN           2471
#define ID_DIRTREEMENU_GOTOWEBPAGE      2472
#define ID_RULEFILE_SORTWORDS           2473
#define ID_RULEFILE_MAKEPHRASES         2474
#define ID_SAVE_ALL                     2475
#define ID_RULEFILE_SAVERUNLOG          2476
#define ID_RULEFILE_SAVE                2477
#define ID_SEQUENCEMENU_DUPLICATE       2478
#define ID_RULEFILE_RUN                 2479
#define ID_RULEFILE_VIEWLOG             2480
#define ID_RULEFILE_HEADER              2481
#define ID_FIND_FORWARD                 2482
#define ID_FIND_BACK                    2483
#define ID_RULEFILE_FINDINLOG           2484
#define ID_RULEFILE_DUPLICATELINE       2485
#define ID_VIEW1                        2486
#define ID_VIEW_BAR1                    2487
#define ID_VIEW_BAR2                    2488
#define ID_VIEW_BAR3                    2489
#define ID_GENERATELOGS                 2490
#define ID_GRAMMAR_EDITEXAMPLES         2491
#define ID_GRAMMAR_ADDRULE              2492
#define ID_GRAMMAR_ADDCONCEPT           2493
#define ID_RUN                          2494
#define ID_URL                          2495
#define ID_URL_COMBOBOX                 2496
#define ID_ADD_URL                      2497
#define ID_LOGFILE_VIEWRULEFILE         2498
#define ID_LOGFILE_FINDINRULEFILE       2499
#define ID_RULEFILE_RUNANDVIEW          2500
#define ID_TEXTVIEW_SELECTANDRUN        2501
#define ID_RULEFILE_CLOSEREST           2502
#define ID_GRAMMAR_ADDTOPCONCEPT        2503
#define ID_TEXT_ADDEXAMPLE              2504
#define ID_LOGFILE_VIEWLOGTREE          2505
#define ID_FILE_NEWANALYZER             2506
#define ID_FILE_OPENANALYZER            2507
#define ID_FILE_SAVEANALYZER            2508
#define ID_FILE_CLOSEANALYZER           2509
#define ID_GEN_ANALYZER                 2510
#define ID_TREE_UP                      2511
#define ID_TREE_DOWN                    2512
#define ID_GRAMMAR_DELETECONCEPT        2513
#define ID_SAVE_KB                      2514
#define ID_LOGFILE_HELP                 2515
#define ID_GRAMMAR_HELP                 2516
#define ID_SEQUENCEMENU_VIEWLOG         2517
#define ID_FINDMENU_CLEAR               2518
#define ID_FINDMENU_OPEN                2519
#define ID_FINDMENU_HELP                2520
#define ID_GEN_DIRTY_AND_RUN            2521
#define ID_GRAMMAR_UPLOADGRAMMAR        2522
#define ID_GRAMMAR_SERVERARCHIVES       2523
#define ID_GRAMMAR_LOCALARCHIVE         2524
#define ID_DIRTREEMENU_ARCHIVETEXT      2525
#define ID_DIRTREEMENU_SERVERARCHIVES   2526
#define ID_DIRTREEMENU_UPLOADTEXT       2527
#define ID_DIRTREEMENU_LOCALARCHIVE     2528
#define ID_SEQUENCEMENU_ARCHIVERULES    2529
#define ID_SEQUENCEMENU_SERVERARCHIVES  2530
#define ID_SEQUENCEMENU_LOCALARCHIVES   2531
#define ID_SEQUENCEMENU_UPLOADRULES     2532
#define ID_GRAMMAR_ARCHIVEGRAMMAR       2533
#define ID_GRAMMAR_EDITRULES            2534
#define ID_FILE_ARCHIVES_LOCAL_ARCHIVE  2535
#define ID_FILE_ARCHIVES_SERVERARCHIVE  2536
#define ID_FILE_ARCHIVES_ARCHIVEANALYZER 2537
#define ID_FILE_ARCHIVES_UPLOADANALYZER 2538
#define ID_GRAMMAR_EDITATTRIBUTES       2539
#define ID_OUTPUTMENU_ADDOUTPUT         2540
#define ID_OUTPUTMENU_EDITATTRIBUTES    2541
#define ID_OUTPUTMENU_DELETE            2542
#define ID_OUTPUTMENU_ARCHIVEOUTPUT     2543
#define ID_OUTPUTMENU_LOCALARCHIVE      2544
#define ID_OUTPUTMENU_SERVERARCHIVE     2545
#define ID_OUTPUTMENU_UPLOADOUTPUT      2546
#define ID_OUTPUTMENU_ADDITEM           2547
#define ID_OUTPUTMENU_PROPERTIES        2548
#define ID_GRAMMAR_PROPERTIES           2549
#define ID_WINDOW_CLOSEALL              2550
#define ID_SEQUENCEMENU_ADDSTUB         2551
#define ID_GRAMMAR_DELETECHILDREN       2552
#define ID_GRAMMAR_ADDLIST              2553
#define ID_GRAMMAR_DELETESAMPLES        2554
#define ID_GRAMMAR_SAVESAMPLEFILE       2555
#define ID_SEQUENCEMENU_HIGHLIGHTMATCHES 2556
#define ID_GRAMMAR_HIGHLIGHTMATCHES     2557
#define ID_RULEFILE_HIGHLIGHTMATCHES    2558
#define ID_RUN_NEXT                     2559
#define ID_ANALYZER_GENERATEALL         2560
#define ID_ANALYZER_GENERATEUNLOCKED    2561
#define ID_ANALYZER_GENERATEDIRTY       2562
#define ID_TEXT_DISPLAYTREE             2563
#define ID_GRAMMAR_VIEWTREE             2564
#define ID_DIRTREEMENU_DELETELOGS       2565
#define ID_GRAMMAR_MARKFORGENERATION    2566
#define ID_HIGHLIGHTING                 2567
#define ID_DIRTREEMENU_REFRESH          2568
#define ID_SEQUENCEMENU_VIEWENTIRETREE  2569
#define ID_TEXT_VIEWOUTPUT              2570
#define ID_TEXT_VIEWENTIRETREE          2571
#define ID_SAMPLEMENU_SORT              2572
#define ID_SAMPLEMENU_GENERATESAMPLES   2573
#define ID_GRAMMAR_ASSOCIATESAMPLEFILE  2574
#define ID_GRAMMAR_OPENSAMPLEFILE       2575
#define ID_GRAMMAR_SYNCHRONIZEWITHFILE  2576
#define ID_GRAMMAR_UPDATE               2577
#define ID_COMBOBOX                     2578
#define ID_DELETE                       2579
#define ID_GRAMMAR_DISASSOCIATEFILE     2580
#define ID_PARSETREE_OPENALL            2581
#define ID_PARSETREE_CLOSEALL           2582
#define ID_PARSETREE_OPENITEMALL        2583
#define ID_PARSETREE_MAKEITEMROOT       2584
#define ID_PARSETREE_DISPLAYENTIRETREE  2585
#define ID_PARSETREE_OPENONELEVEL       2586
#define ID_PARSETREE_FIND               2587
#define ID_FIND                         2588
#define ID_GRAMMAR_FIND                 2589
#define ID_STOP_PROCESS                 2590
#define ID_SEQUENCEMENU_PROPERTIES      2591
#define ID_GRAMMAR_REFRESH              2592
#define ID_SEQUENCEMENU_VIEWTREEMATCHES 2593
#define ID_PARSETREE_HIGHLIGHTTEXT      2594
#define ID_VERBOSE_MODE                 2595
#define ID_NEXT_TEXT                    2596
#define ID_PREV_TEXT                    2597
#define ID_PARSETREE_MAKEPARENTROOT     2598
#define ID_PAGE_MODE                    2599
#define ID_DIRTREEMENU_MASK             2600
#define ID_GRAMMAR_ADD_STUB             2601
#define ID_TREE                         2602
#define ID_PROCESSED_TEXT               2603
#define ID_RULE_FILE                    2604
#define ID_DUMP                         2605
#define ID_OUTPUT                       2606
#define ID_RULEFILE_NLPHELP             2607
#define ID_NEW_BROWSER                  2608
#define ID_RULEFILE_SELECTPASS          2609
#define ID_KNOWLEDGE_BASE               2610
#define ID_KNOWLEDGE_DELETE             2612
#define ID_KNOWLEDGE_DELETECHILDREN     2613
#define ID_KNOWLEDGE_FIND               2614
#define ID_KNOWLEDGE_ATTRIBUTES         2615
#define ID_KNOWLEDGE_PHRASES            2616
#define ID_KNOWLEDGE_ADDPHRASE          2617
#define ID_BUTTON33023                  2618
#define ID_UP                           2619
#define ID_DOWN                         2620
#define ID_KB_DOWN                      2621
#define ID_TAB_SAVE                     2622
#define ID_SLOT_FILL                    2623
#define ID_TEXT_CONVERTTOOUTPUT         2624
#define ID_RUN_HTML                     2625
#define ID_WEBPAGE                      2626
#define ID_RULEFILE_STRINGTORULE        2627
#define ID_SEQUENCEMENU_VIEWFULLTREE    2628
#define ID_TREE_CONCEPT                 2629
#define ID_SPIDER                       2630
#define ID_TEXT_SORTTEXT                2631
#define ID_BROWSER_BACK                 2632
#define ID_BROWSER_SAVEASTEXT           2633
#define ID_RULEFILE_INSERT_RULES        2634
#define ID_RULEFILE_INSERT_POST         2635
#define ID_RULEFILE_INSERT_XWHITE       2636
#define ID_RULEFILE_INSERT_POSTRULE     2637
#define ID_KB_UP                        2638
#define ID_BROWSER_OPENURL              2639
#define ID_TOOLS_KBTOOLBAR              2640
#define ID_TOOLS_BROWSERTOOLBAR         2641
#define ID_TOOLS_TABTOOLBAR             2642
#define ID_TOOLS_FIND                   2643
#define ID_SAVE                         2644
#define ID_RULEFILE_CONVERT_STRINGTOGENERALRULE 2645
#define ID_RULEFILE_ADD_MATCHES         2646
#define ID_RULEFILE_ADD_EXCEPT          2647
#define ID_RULEFILE_ADD_FAILS           2648
#define ID_RULEFILE_ADD_OPTIONAL        2649
#define ID_RULEFILE_ADD_STAR            2650
#define ID_RULEFILE_ADDREMOVE_S         2651
#define ID_RULEFILE_CONVERT_ONELINETOMULTIPLE 2652
#define ID_RULEFILE_ADDREMOVE_MAX       2653
#define ID_RULEFILE_ADDREMOVE_MIN       2654
#define ID_RULEFILE_CHANGE_XWILD        2655
#define ID_RULEFILE_CHANGE_XNUM         2656
#define ID_RULEFILE_CHANGE_XALPHA       2657
#define ID_RULEFILE_ADDREMOVE_TRIG      2658
#define ID_RULEFILE_INSERT_XPUNCT       2659
#define ID_RULEFILE_ADDREMOVE_TREE      2660
#define ID_RULEFILE_ADDREMOVE_LOOKAHEAD 2661
#define ID_RULEFILE_INSERT_XALPHA       2662
#define ID_WORDNET                      2663
#define ID_RULEFILE_ADDREMOVE_LAYER     2664
#define ID_DIRTREEMENU_DICTIONIZE       2665
#define ID_DIRTREEMENU_TOOLS_WORDNET    2666
#define ID_RULEFILE_CONVERT_REFORMATRULE 2667
#define ID_KNOWLEDGE_MAKEROOT           2668
#define ID_KNOWLEDGE_UP                 2670
#define ID_DIRTREEMENU_TEXTFILEINFO     2671
#define ID_KNOWLEDGE_GENERATEALL        2672
#define ID_KNOWLEDGE_SAVE               2673
#define ID_COMPILE                      2674
#define ID_KNOWLEDGE_DOWN               2675
#define ID_RULEFILE_ADDREMOVE_ONE       2676
#define ID_RULEFILE_CHANGETO_XWHITE     2677
#define ID_RULEFILE_INSERTLINE_XWHITE   2678
#define ID_RULEFILE_INSERTLINE_XALPHA   2679
#define ID_RULEFILE_INSERTLINE_XNUM     2680
#define ID_RULEFILE_INSERTLINE_XWILD    2681
#define ID_RULEFILE_ADDREMOVE_PLUS      2682
#define ID_PARSETREE_EDITDICTIONARYENTRY 2683
#define ID_TEXT_EDITDICTIONARYATTRIBUTES 2684
#define ID_TOOLS_DEBUGTOOLBAR           2685
#define ID_RULEFILE_DELETELINE          2686
#define ID_DICTIONARY                   2687
#define ID_DICTIONRAYWORDS_MARKAS_ADJECTIVE 2688
#define ID_DICTIONRAYWORDS_MARKAS_ADVERB 2689
#define ID_DICTIONRAYWORDS_MARKAS_NOUN_COUNT 2690
#define ID_DICTIONRAYWORDS_MARKAS_NOUN_NOCOUNT 2691
#define ID_DICTIONRAYWORDS_MARKAS_NOUN_BOTH 2692
#define ID_DICTIONRAYWORDS_MARKAS_VERB_TRANSITIVE 2693
#define ID_DICTIONRAYWORDS_MARKAS_VERB_INTRANSITIVE 2694
#define ID_KB_DICTIONARY                2695
#define ID_FILE_SAVEANALYZERAS          2696
#define ID_DIRTREEMENU_TOOLS_HEXVIEWER  2697
#define ID_DIRTREEMENU_TOOLS_ASCIITABLE 2698
#define ID_TEXT_TOOLS_ASCIITABLE        2699
#define ID_TEXT_TOOLS_DICTIONIZE        2700
#define ID_TEXT_TOOLS_HEXVIEWER         2701
#define ID_TEXT_TOOLS_MASK              2702
#define ID_TEXT_TOOLS_TEXTFILEINFO      2703
#define ID_TEXT_TOOLS_DICTIONARYLOOKUP  2704
#define ID_TOOLS_HEXVIEWER              2705
#define ID_TOOLS_ASCIITABLE             2706
#define ID_TOOLS_TEXTFILEINFO           2707
#define ID_TOOLS_CHARACTERVIEWER        2708
#define ID_DIRTREEMENU_TOOLS_CHARACTERVIEWER 2709
#define ID_SEQUENCEMENU_ADDPASS_FRED    2710
#define ID_RULEFILE_INSERTLINE_XSTART   2711
#define ID_TEXT_EMAIL                   2712
#define ID_TOOLS_EMAIL                  2713
#define ID_DIRTREEMENU_TOOLS_EMAIL      2714
#define ID_DIRTREEMENU_ADD_TOPLEVEL_FOLDER 2715
#define ID_DIRTREEMENU_ADD_TOPLEVEL_EXISTINGTEXTFILE 2716
#define ID_DIRTREEMENU_ADD_TOPLEVEL_NEWTEXTFILE 2717
#define ID_SET_PAGES                    2718
#define ID_SEQUENCEMENU_ADD_FOLDER      2719
#define ID_SEQUENCEMENU_ADD_MAIN        2720
#define ID_SEQUENCEMENU_ADD_TOPLEVEL_MAIN 2721
#define ID_SEQUENCEMENU_ADD_TOPLEVEL_NEW 2722
#define ID_SEQUENCEMENU_ADD_TOPLEVEL_PASS_FRED 2723
#define ID_SEQUENCEMENU_ADD_TOPLEVEL_EXISTINGPASS 2724
#define ID_SEQUENCEMENU_ATTRIBUTES      2725
#define ID_DIRTREEMENU_ATTRIBUTES       2726
#define ID_SEQUENCEMENU_ADD_TOPLEVEL_FOLDER 2727
#define ID_SEQUENCEMENU_ADD_STUB        2728
#define ID_BATCH_MODE                   2729
#define ID_TEXT_WRAPTEXT                2730
#define ID_RULEFILE_COMMENTUNCOMMENT    2731
#define ID_TEXT_GENERATERULE            2732
#define ID_RULEFILE_INSERT_DUMPFILE     2733
#define ID_DISPLAY_TOOLBARS_FILE        2734
#define ID_GRAMMAR_SAMPLEFILE_CONSOLIDATE 2735
#define ID_GRAMMAR_SAMPLEFILE_OPEN      2736
#define ID_GRAMMAR_SAMPLEFILE_SET       2737
#define ID_GRAMMAR_SAMPLEFILE_UPDATE    2738
#define ID_GRAMMAR_ADD_FOLDER           2739
#define ID_GRAMMAR_ADD_LABEL            2740
#define ID_GRAMMAR_ADD_RULE             2741
#define ID_GRAMMAR_SAMPLEFILE_IMPORT    2742
#define ID_GRAMMAR_SAMPLEFILE_EXPORT    2743
#define ID_DISPLAY_TABSWINDOW           2744
#define ID_DISPLAY_OUTPUTWINDOW         2745
#define ID_DISPLAY_FINDWINDOW           2746
#define ID_LOGFILE_RULEFILE_FINDLOCAL   2747
#define ID_SAVE_AS                      2748
#define ID_ACCEL33235                   2749
#define ID_TEXT_FINDAGAIN               2750
#define ID_TEXT_FINDLOCAL               2751
#define ID_LOGFILE_FINDLOCAL            2752
#define ID_LOGFILE_FINDAGAIN            2753
#define ID_RULEFILE_INSERT_XNUM         2754
#define ID_BUTTON33242                  2755
#define ID_COMPILE_KB                   2756
#define ID_KB_COMPILEKB                 2757
#define ID_BUTTON33245                  2758
#define ID_ANALYZER_COMPILEANALYZER     2759
#define ID_BUTTON33250                  2760
#define ID_REPLACE_IN_FILES             2761
#define ID_RULEFILE_HELPONSELECTION     2762
#define ID_TREE_SEMANTICS               2763
#define ID_VIEW_TREESEMANTICSMODE       2764
#define ID_ATTRIBUTEEDITOR              2765
#define ID_TEXT_TOOLS_JUMBLE            2766
#define ID_DIRTREEMENU_TOOLS_JUMBLE     2767
#define ID_ATTRIBUTE_EDITOR             2768
#define ID_TEXT_DICTIONARY_ADDWORDS     2769
#define ID_TEXT_DICTIONARY_KBATTRIBUTES 2770
#define ID_DIRTREEMENU_DICTIONARY_ADDWORDS 2771
#define ID_TOOLS_ADDWORDS               2772
#define ID_TOOLS_KBATTRIBUTES           2773
#define ID_VIEW_TREEOFFSETSMODE         2774
#define ID_KNOWLEDGE_KBMODULAR_LOAD     2775
#define ID_KNOWLEDGE_KBMODULAR_SAVE     2776
#define ID_PARSETREE_VIEWRULEFIRED      2777
#define ID_FONTS                        2778
#define ID_DICTIONARY_URL_LOOKUP_BASE   2779
#define ID_DICTIONARY_URL_LOOKUP_MAX    2780
#define ID_TOOLS_DICTIONARY_URL_LOOKUP_BASE 2781
#define ID_TOOLS_DICTIONARY_URL_LOOKUP_MAX 2782
#define ID_INDICATOR_LINECOL            2783
#define ID_TAB_TOOLBAR                  2784
#define ID_KNOWLEDGE_TOOLBAR            2785
#define ID_DEBUG_TOOLBAR                2786
#define ID_BROWSER_TOOLBAR              2787
#define ID_VIEW_WORKSPACE               2788
#define ID_VIEW_OUTPUT1                 2789
#define ID_VIEW_OUTPUT2                 2790
#define ID_FILE_RECENTANALYZERS         2791
#define IDM_ABOUTBOX                    2794
#define IDI_KB                          2797
#define IDD_ABOUTBOX                    2798
#define IDI_PAT                         2798
#define IDI_TREE                        2799
#define ID_DUMP_LIST                    2800
#define IDR_ANALYZE_LOG                 2800
#define IDR_ANALYZER_TOOLBAR            2801
#define IDR_SYNTAXEDIT_MENU             2801
#define IDR_GRAMMAR_TOOLBAR             2802
#define IDI_GLOBE                       2804
#define IDI_MAINFRAME                   2820
#define IDB_SPLASH                      2821
#define ID_FILE_GOTO                    32771
#define ID_FILE_SAVEALL                 32772
#define ID_TOOLS_BOOKMARK               32773
#define ID_TOOLS_BREAKPOINT             32774
#define ID_EDIT_FINDINFILES             32776
#define ID_COMBO_FIND                   32777
#define ID_TOOLS_NEXT_BOOKMARK          32777
#define ID_HELP_SEARCH                  32778
#define ID_BUILD_COMPILE                32779
#define ID_BUILD_STOP                   32780
#define ID_BUILD_EXECUTE                32781
#define ID_BUILD_GO                     32782
#define ID_EDIT_BREAKPOINT              32783
#define ID_BUILD_BUILD                  32784
#define ID_TOOLS_PREV_BOOKMARK          32784
#define ID_WIZBAR_CLASS                 32786
#define ID_WIZBAR_FILTER                32787
#define ID_WIZBAR_MEMBERS               32788
#define ID_WIZBAR_ACTIONS               32789
#define ID_EDIT_TABIFY                  32789
#define ID_WIZBAR_GOTOFUNCTIONDECLARATION 32790
#define ID_EDIT_UNTABIFY                32790
#define ID_WIZBAR_GOTOFUNCTIONDEFINITION 32791
#define ID_EDIT_WHITESPACE              32791
#define ID_WIZBAR_ADDWINDOWSMESSAGEHANDLER 32792
#define ID_TOOLS_OPTIONS                32792
#define ID_WIZBAR_ADDVIRTUALFUNCTION    32793
#define ID_EDIT_COLLAPSEALL             32793
#define ID_WIZBAR_DELETE                32794
#define ID_EDIT_EXPANDALL               32794
#define ID_WIZBAR_GOTOCLASSDEFINITION   32795
#define ID_WIZBAR_NEWCLASS              32796
#define ID_EDIT_UPPERCASE               32796
#define ID_WIZBAR_NEWFORM               32797
#define ID_WIZBAR_WIZARDBARHELP         32798
#define ID_EDIT_LOWERCASE               32798
#define ID_WIZBAR_ADDMEMBERFUNCTION     32799
#define ID_BUILD_SELECT                 32800
#define ID_BUILD_ACTIVE                 32801
#define ID_EDIT_FIND_SILENT             32801
#define IDC_TAB_PROPERTIES              32802
#define ID_FILE_CLOSEALL                32803
#define ID_INDICATOR_ROWCOL             32805
#define ID_EDIT_READONLY                32806
#define ID_INSERT_ATL                   32807
#define ID_RESNEW_DIALOG                32808
#define ID_RESOURCE_MENU                32809
#define ID_RESOURCE_CURSOR              32810
#define ID_RESOURCE_ICON                32811
#define ID_TOOLS_RELOADSYNTAX           32811
#define ID_RESOURCE_BITMAP              32812
#define ID_TOOLS_RELOADSYNTAX2INIMODE   32812
#define ID_TOOLS_RELOADSYNTAXMODE       32813
#define ID_RESOURCE_ACCEL               32814
#define ID_RESOURCE_STRING              32815
#define ID_RESOURCE_VERSION             32816
#define ID_RESOURCE_SYMBOLS             32817
#define ID_RESOURCE_DIALOG              32818
#define ID_EDIT_TOGGLE                  32819
#define ID_EDIT_MOVE                    32820
#define ID_EDIT_PREV                    32821
#define ID_EDIT_INCREASE                32824
#define ID_EDIT_DECREASE                32825
#define ID_EDIT_WHITESP                 32826
#define ID_EDIT_NEXT                    32827
#define ID_EDIT_CLEARBM                 32828
#define ID_DEBUG_RESTART                32829
#define ID_DEBUG_STOP                   32830
#define ID_DEBUG_BREAK                  32831
#define ID_DEBUG_APPLY                  32832
#define ID_DEBUG_SHOWNEXT               32833
#define ID_DEBUG_STEPINTO               32834
#define ID_DEBUG_STEPOVER               32835
#define ID_DEBUG_STEPOUT                32836
#define ID_DEBUG_RUNTO                  32837
#define ID_DEBUG_QUICKWATCH             32838
#define ID_DEBUG_WATCH                  32839
#define ID_DEBUG_VARIABLES              32840
#define ID_DEBUG_REGISTERS              32841
#define ID_DEBUG_MEMORY                 32842
#define ID_DEBUG_CALLSTACK              32843
#define ID_DEBUG_DISASSEMBLY            32844
#define ID_BROWSE_DEF                   32845
#define ID_BROWSE_REF                   32847
#define ID_BROWSE_PREV                  32848
#define ID_BROWSE_NEXT                  32849
#define ID_BROWSE_POP                   32850
#define ID_BROWSE_OUTLINE               32851
#define ID_BROWSE_DEFANDREF             32852
#define ID_BROWSE_DERIVED               32853
#define ID_BROWSE_BASE                  32854
#define ID_BROWSE_CALLGRAPH             32855
#define ID_BROWSE_CALLERSGRAPH          32856
#define ID_DBASE_RUN                    32857
#define ID_DBASE_ADD                    32858
#define ID_DBASE_INSERT                 32859
#define ID_FILE_OPENWORKSPACE           32860
#define ID_FILE_SAVEWORKSPACE           32861
#define ID_FILE_CLOSEWORKSPACE          32862
#define ID_EDIT_GOTO                    32866
#define ID_EDIT_BREAKPOINTS             32867
#define ID_VIEW_CLASSWIZARD             32868
#define ID_VIEW_RESOURCEINCLUDES        32869
#define ID_VIEW_REFRESH                 32871
#define ID_VIEW_PROPERTIES              32872
#define ID_INSERT_NEWCLASS              32873
#define ID_INSERT_NEWFORM               32874
#define ID_INSERT_RESOURCE              32875
#define ID_INSERT_RESOURCECOPY          32876
#define ID_PROJECT_ADDTOPROJECT_NEW     32878
#define ID_PROJECT_ADDTOPROJECT_NEWFOLDER 32879
#define ID_PROJECT_ADDTOPROJECT_FILES   32880
#define ID_PROJECT_ADDTOPROJECT_COMPONENTSANDCONTROLS 32881
#define ID_PROJECT_DEPENDENCIES         32882
#define ID_PROJECT_SETTINGS             32883
#define ID_PROJECT_EXPORTMAKEFILE       32884
#define ID_PROJECT_INSERTPROJECTINTOWORKSPACE 32885
#define ID_BUILD_REBUILDALL             32887
#define ID_BUILD_BATCHBUILD             32888
#define ID_BUILD_CLEAN                  32889
#define ID_BUILD_STARTDEBUGGING_ATTACHTOPROCESS 32890
#define ID_BUILD_DEBUGGERREMOTECONNECTION 32891
#define ID_BUILD_SETACTIVECONFIGURATION 32892
#define ID_BUILD_CONFIGURATIONS         32893
#define ID_BUILD_PROFILE                32894
#define ID_TOOLS_SOURCEBROWSER          32895
#define ID_TOOLS_CLOSESOURCEBROWSER     32896
#define ID_WINDOW_DOCKINGVIEW           32898
#define ID_WINDOW_CLOSE                 32899
#define ID_WINDOW_NEXT                  32901
#define ID_WINDOW_PREV                  32902
#define ID_HELP_CONTENTS                32917
#define ID_HELP_USEEXTENSIONHELP        32919
#define ID_HELP_KEYBOARDMAP             32920
#define ID_HELP_TECHNICALSUPPORT        32922
#define ID_HELP_CODEJOCKSOFTWAREONTHEWEB_CODEJOCKSOFTWAREHOMEPAGE 32923
#define ID_FILE_MRU_WORKSPACE           32925
#define ID_VIEW_OUTPUT                  32926
#define IDC_TAB_CLASSVIEW               32928
#define IDC_TAB_RESOURCEVIEW            32929
#define IDC_TAB_FILEVIEW                32930
#define ID_GO                           32935
#define ID_GO_URL                       32936
#define ID_KNOWLEDGE_UPDATE             32937
#define ID_RULEFILE_FINDLOCAL           32940
#define ID_KNOWLEDGE_ADDCONCEPTS        32941
#define ID_Menu                         32942
#define ID_VIEW_TREETEXTMODE            32944
#define ID_EDIT_SELECTALL               32948
#define ID_SELECTALL_CTRL               32949
#define ID_BUTTON32957                  32957
#define ID_ADD_EXISTINGFOLDER           32958
#define ID_RECENT_COMBO                 32959
#define ID_VIEW_FULLSCREEN              32960
#define ID_DIRTREEMENU_EXPLOREDIRECTORY 32961
#define ID_TEXT_VIEWTREEOFSELECTED      32962
#define ID_LOGMENU_CLEAR                32963
#define ID_LOGMENU_OPEN                 32964
#define ID_ANALYZELOGMENU_CLEAR         32965
#define ID_TOOLS_THEME_OFFICE2003THEME  32966
#define ID_TOOLS_THEME_CUSTOMTHEME      32967
#define ID_THEME_VISUALSTUDIO2008       32968
#define ID_THEME_VISUALSTUDIO2010       32969
#define ID_THEME_OFFICE2003THEME        32970
#define ID_THEME_OFFICE2003             32971
#define ID_BUTTON32972                  32972
#define ID_BUTTON32973                  32973
#define ID_BUTTON32974                  32974
#define ID_FILE_RECENTFILES             32976
#define ID_Menu32981                    32981
#define ID_RECENTFILES_RECENTFILES      32982
#define ID_RECENTANALYZERS_MOOSE        32983
#define ID_FILE_ANALYZERS               32984
#define ID_ANALYZERS_MOOSE              32985
#define ID_ANALYZERS_FRED               32986
#define ID_RECENTANALYZERS_ANALYZER1    32987
#define ID_RECENTANALYZERS_ANALYZER     32988
#define ID_DIRTREEMENU_ADDEXISTINGFOLDER 32989
#define ID_SEQUENCEMENU_DELETEPASSES    32990
#define ID_TOOLS_RULEEDITOPTINOS        32991
#define ID_TOOLS_RULEEDITOPTIONS        32992
#define ID_RULEFILE_REFORMATRULE        32993
#define ID_VIEW_ANALYZERVIEW            32994
#define ID_VIEW_TEXTVIEW                32995
#define ID_VIEW_GRAMMARVIEW             32996
#define ID_CLEAR_URL                    32997
#define ID_FIND_IN_FILES                32998
#define ID_NODE_SEMANTICS               32999
#define ID_VIEW_EDITOROPTIONS           33000
#define ID_VIEW_OPTIONS                 33001
#define ID_VIEW_OPTIONS33003            33003
#define ID_TEXT_WORDWRAPON              33004
#define IDC_BAR_OUTPUT                  59580
#define IDC_BAR_WORKSPACE               59581
#define IDC_BAR_WATCH                   59582
#define IDC_BAR_CALLSTACK               59583
#define IDC_BAR_MEMORY                  59584
#define IDC_BAR_VARIABLES               59585
#define IDC_BAR_REGISTERS               59586
#define IDC_BAR_DISASSEMBLY             59587
#define IDR_PANE_OUTPUT                 59600
#define IDR_PANE_WORKSPACE              59601
#define IDR_PANE_ANALYZER               59602
#define IDR_PANE_GRAMMAR                59603
#define IDR_PANE_TEXT                   59604
#define IDR_PANE_FIND                   59605
#define IDR_PANE_FIND2                  59606
#define IDR_PANE_ANALYZE                59607
#define IDR_PANE_LOG                    59608
#define ID_WINDOW_WINDOWLIST            65289

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2822
#define _APS_NEXT_COMMAND_VALUE         33005
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
